# Generated by Django 3.2.13 on 2023-06-11 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_payment_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='user',
        ),
        migrations.AddField(
            model_name='payment',
            name='email',
            field=models.EmailField(default='hi@gmail.com', max_length=255, unique=True, verbose_name='Email'),
            preserve_default=False,
        ),
    ]
